### ISSUE TITLE
Please add an example of using GDI+ backend

### ISSUE THREAD

**Issue by Fuckoffee** [snuk182/nuklear-rust#1]

**Comment by snuk182** [comment]
The original Nuklear [has](https://github.com/vurtun/nuklear/tree/master/demo/gdip) a GDI+ demo. Need to merge it with [backend-less example](https://github.com/snuk182/nuklear-test/tree/old_no_backend), utilizing the raw winapi bindings + extract a GDI+ backend then. Will see how fast I can do this!
Also [Windows subsystem support](https://github.com/rust-lang/rfcs/blob/master/text/1665-windows-subsystem.md) may influence.

**Comment by snuk182** [comment]
While there is no GDI+ bindings (for objective reasons), would GDI backend be reasonable?

**Comment by Fuckoffee** [comment]
I think that GDI or Direct2D will be a good backend

**Comment by snuk182** [comment]
Done with https://github.com/snuk182/nuklear-backend-gdi .
Sample https://github.com/snuk182/nuklear-test/tree/gdi .
