### ISSUE TITLE
Possibly rename crate to "nuklear"?

### ISSUE THREAD

**Issue by daboross** [snuk182/nuklear-rust#10]
This would be more of a bikeshed than anything else, but it's been a convention to *not* have crate names on crates.io or rust package names start with `rust_`, as this pollutes code with useless information.

There are two distinct possibilities for changing this though, if you were interested in it:

- A. rename the rust package to `nuklear`, keep the *crate* name `nuklear-rust`.

  Crate would be used like:
  ```rust
  // Cargo.toml:
  nuklear-rust = "0.3"
  // lib.rs:
  extern crate nuklear;
  ```

- B. rename both to `nuklear`, and publish a small release on crates.io for `nuklear-rust` marking it as deprecated, with a README pointing to the `nuklear` crate.

  Crate would be used like:
   ```rust
   // Cargo.toml:
   nuklear = "0.3"
   // lib.rs:
   extern crate nuklear;
   ```

- C. Don't change anything. Possibly recommend renaming on usage?

  Crate could be used like:
  ```rust
  // Cargo.toml:
  nuklear-rust = "0.3"
  // lib.rs:
  extern crate nuklear_rust as nk;
  ```

I would prefer A or B, but any is an alright option. There's nothing inherently bad about *-rust or *-rs crate names besides community bias. A. would be a lot less churn over B., as it would still be the same crates.io package, so that might be the best option?

I should note that none of this is suggesting renaming the project name, nor the repository name, just the name to use _in rust programs_. I definitely agree with it being called "nuklear-rust" everywhere else - it's just a bit redundant from within rust. It's a large convention to have projects named `xxx-rs` or `xxx-rust` (with matching git repositories) with just `xxx` as the name in crates.io and as the package name.

**Comment by vitvakatu** [comment]
Option A seems the most preferable here
