### ISSUE TITLE
Format examples according to the Rust guidelines

### ISSUE THREAD

**Issue by mruegenberg** [snuk182/nuklear-rust#13]
Hello,
not sure if I just didn't find it, but there seems to be no example, even though one is mentioned in the README.
Having one would (even if it's just a _Hello World_), of course, be super-useful for quickly evaluating the library.

**Comment by ghost** [comment]
In fact, there are some links in the README pointing to https://github.com/snuk182/nuklear-test, which seems to be a test project by @snuk182

**Comment by snuk182** [comment]
Hi @mruegenberg ,
@Ealhad has right, the readme contains the links to the various examples. I'll copy them here and mark bold:

* [gfx](https://github.com/snuk182/nuklear-backend-gfx) for [GFX 3D drawing engine](https://github.com/gfx-rs/gfx) **(examples: [OpenGL](https://github.com/snuk182/nuklear-test), [DX11](https://github.com/snuk182/nuklear-test/tree/dx11))**
* [glium](https://github.com/snuk182/nuklear-backend-glium) for [glium 3D drawing engine](https://github.com/tomaka/glium) **(example: [here](https://github.com/snuk182/nuklear-test/tree/glium))**
* [GDI](https://github.com/snuk182/nuklear-backend-gdi) for [WinAPI GDI](https://msdn.microsoft.com/en-us/library/windows/desktop/dd145203(v=vs.85).aspx) **(example: [here](https://github.com/snuk182/nuklear-test/tree/gdi))**
All examples are based on the [extended example](https://github.com/vurtun/nuklear/blob/master/example/extended.c) of the original library.

The reason why I did not use the standard `examples` feature of Rust project is a structural complexity, which I could not predict at the moment of project creation. Maybe it is indeed better to move the examples backend-wise.

**Comment by ghost** [comment]
> Having one would (even if it's just a Hello World), of course, be super-useful for quickly evaluating the library.

I think this was a very valid point. The README should probably include a very simple example, and a “Hello World” should be perfect for that.

**Comment by snuk182** [comment]
@Ealhad ,
That sounds challenging, as the minimal amount of code to achieve the HelloWorld functionality does not differ much from the one contained in the current examples (plus different drawing backends). What I can do is document the existing examples better + move them to the backends' `examples` dirs accordingly.

**Comment by ghost** [comment]
Yes, after trying I realized that myself. I guess moving the examples would be fine.

**Comment by snuk182** [comment]
After giving it a try it looks like it is impossible to make a project-based example (contrary to a single .rs file) without forming the whole project as Cargo workspace. Closing as of now.
