### ISSUE TITLE
Fix raw pointer issues at the Rust heap allocator

### ISSUE THREAD

**Issue by Xaeroxe** [snuk182/nuklear-rust#15]
This makes me sad because I prefer the stable toolchain.  Would it be possible to make this without using nightly only features?

**Comment by Xaeroxe** [comment]
Possibly just the example.  I'll post an issue there.

**Comment by snuk182** [comment]
There [are](https://github.com/snuk182/nuklear-test/issues/6#issuecomment-389649331) actually the problems with allocator API due to the raw pointers policy change. Will fix it in the scope of this ticket (once I have a free minute :cry: ).
Thanks @Xaeroxe for pointing this out!
