### ISSUE TITLE
Styles

### ISSUE THREAD

**Issue by Catvert** [snuk182/nuklear-rust#16]
Hi ! 
I'm trying your library and it works very well ! I've just got an issue (?) while styling my ui. When I've tried for example to style buttons, I did the following : 

```rust
 ctx.style().button().set_hover(StyleItem::color(color_rgba(...)));
```
Unfortunately, the button() method doesn't return a mutable ref so I can't mutate the style. However, I've seen that the window method return a mut ref, so why not for buttons and other items? Is there an other way to achieve that?

Thanks for your help.

**Comment by snuk182** [comment]
Hello, and thanks for the ticket!
Will add missing methods ASAP. Did not use styles so far, that is why were not concerned about mutators.

**Comment by snuk182** [comment]
Fixed with https://github.com/snuk182/nuklear-rust/commit/2d23e27cadbfe878b81df9cbb940851a2502e40a . Please update nkr version to 0.5 and use mutable accessors for style.
