### ISSUE TITLE
Linux or SDL2

### ISSUE THREAD

**Issue by zwykl3** [snuk182/nuklear-rust#21]
Is possible run this in SDL2 or native in linux?

**Comment by snuk182** [comment]
Should work with [Vulkan](https://github.com/snuk182/nuklear-test/tree/wgpurs), [gfx-pre-ll + OpenGL](https://github.com/snuk182/nuklear-test), [glium + glutin](https://github.com/snuk182/nuklear-test/tree/glium) out of the box. Did not run it on Linux for a while, as using Win primarily, but at the moment of active usage it was working at Ubuntu 17.something. SDL is not supported.

**Comment by zwykl3** [comment]
I'm not using Windows.
Please run linux on Virtual box and create a 'makefile' ;)
Your code are very good

**Comment by snuk182** [comment]
Um. Why makefile? Starts with `cargo run` as usual.
Surprisingly it worked in VM:
![image](https://user-images.githubusercontent.com/493209/57584997-3b6de700-74e2-11e9-822a-db0fe58d7274.png)
![image](https://user-images.githubusercontent.com/493209/57585003-5e989680-74e2-11e9-9b78-22512c1549f7.png)

**Comment by snuk182** [comment]
Closing this, as Linux solution is provided, and there's a separate ticket for SDL.
