### ISSUE TITLE
No way of accessing clipboard struct on context

### ISSUE THREAD

**Issue by GideonUng** [snuk182/nuklear-rust#22]
On the context struct the internal nk_context struct is not accessable. but some members should be mutably accessable according to nuklear.

From the nk_context struct in c:
/* public: can be accessed freely */

And without that access i dont see a way to setup the clipboard callbacks

**Comment by snuk182** [comment]
Got it.

**Comment by GideonUng** [comment]
I think Input and Style already have an accessor function. so this could probably also be done for the other couple structs that are marked as public on nk_context

**Comment by snuk182** [comment]
Added some contents with https://github.com/snuk182/nuklear-rust/commit/d8946a800c13060a0dc686049f47bfa7414c9d99 . All that left requires far more effort, so I gonna make it separately. Please try v0.6.2 at crates.

**Comment by GideonUng** [comment]
Hey thanks cool stuff and man that was fast.

**Comment by snuk182** [comment]
Just a luck as it's weekend and I'm free :) Have fun.
