### ISSUE TITLE
Crash on i686 target

### ISSUE THREAD

**Issue by lynnux** [snuk182/nuklear-rust#27]
At first, I build the gdi demo by `nightly-x86_64-pc-windows-msvc`, all good, but got crash when build by `nightly-i686-pc-windows-msvc`. And I debugged to figure out the crash palce is `nk_init`, relate to `nk_handle`. In nuklear-sys-4.0.4:
```
pub union nk_handle {
    pub ptr: *mut ::std::os::raw::c_void,
    pub id: ::std::os::raw::c_int,
    _bindgen_union_align: u64,   
}
```
this cause nk_handle take 8 bytes in i686 build, but the C def is 
```
typedef union {void *ptr; int id;} nk_handle;
```
it only take 4 bytes in i686 build, so that's the problem!

**Comment by snuk182** [comment]
Hi @lynnux , thanks for the ticket.

Bindgen is so Bindgen, unfortunately. I hope to get a x86 machine/VM ASAP and look closer onto the whole family of such issues. Of course, if you have a solution, I always appreciate a MR.

**Comment by snuk182** [comment]
Hi @lynnux , couldn't you please update the deps and give a try?

**Comment by lynnux** [comment]
@snuk182 thanks, it 's working great!
