### ISSUE TITLE
Is it possible to remove default Titlebar and other window chrome?

### ISSUE THREAD

**Issue by ILikeTeaALot** [snuk182/nuklear-rust#29]
I've quite liked my (admittedly _super_ limited) experience with this so far, and was wondering if there was a way to hide the default chrome on windows (not just on Windows) and then create my own titlebar and controls and such

I'm unsure whether this is something that hasn't been implemented or if I've just missed something, any help/advice/etc would be appreciated :D

✌️

**Comment by snuk182** [comment]
Hm. Not sure if you are asking about the window decoration for the parts created with Nuklear, or the system window decorations. For the first - I haven't tried that, frankly speaking, but think it is possible, and just depends on how you declare those. For the second - the answer severely depends on the Nuklear backend you use. For instance, for `nuklear-backend-gfx`, while using `glium as a window context provider` [this may help](https://docs.rs/glutin/0.7.4/glutin/struct.WindowBuilder.html#method.with_decorations). Same for [`winit`](https://docs.rs/winit/0.20.0-alpha4/winit/window/struct.WindowBuilder.html#method.with_decorations). For GDI you need to look for the same window context setup in `winapi`, fist in the native API, then whether this API is supported in `winapi` crate. Hope this helps.
