### ISSUE TITLE
Unideomatic naming convention

### ISSUE THREAD

**Issue by vitvakatu** [snuk182/nuklear-rust#4]
I'm a bit confused with all these `Nk` in front of every type. It serves absolutely no purpose because Rust has namespaces, and the common usage looks like:
```rust
use nuklear_rust as nk;
//....
nk::NkAllocator::new_vec();
```

**Comment by snuk182** [comment]
Roger that.

**Comment by snuk182** [comment]
Won't fix the constants and enum variants, because they are mostly reexported from `*-sys` so I'd keep these names consistent through the whole lib.
