### ISSUE TITLE
Use Drop to automatically free things?

### ISSUE THREAD

**Issue by daboross** [snuk182/nuklear-rust#8]
Hi,

I'm getting used to using this library, and I was wondering one thing: if all nuklear types have `free()` methods, why not just implement `Drop`?

Drop would run at the end of where the variable exists, so it would make the library much easier to use without creating memory leaks. At least, that's my understanding.

Is there a technical reason which stops these types from implementing `Drop` and instead requires them to have `free` methods?

I don't want to assume anything, but if you're less experienced with the rust idioms I can make more issues on things I'd notice and potential submit PRs to fix them if you see the changes as OK in the FFI side of things.

**Comment by snuk182** [comment]
Cheers.
Any suggestions are highly welcome!
So far I've just translated the C api with minimal changes, to get used to Rust FFI and C-style libraries.

**Comment by daboross** [comment]
Sounds good, thanks! Glad to have an active library like this.
