### ISSUE TITLE
Documentation on initializing fonts?

### ISSUE THREAD

**Issue by daboross** [snuk182/nuklear-rust#9]
Just trying to run a simple example, but I'm having a bit of trouble with initializing everything. I can do most of it through `nuklear-rust`, but I can't seem to find how I should initialize a `nuklear_rust::NkUserFont`.

Here's what I have right now:

```rust
extern crate glium;
extern crate nuklear_backend_glium;
extern crate nuklear_rust as nk;

use glium::glutin;

fn main() {
    let mut glutin_events_loop = glutin::EventsLoop::new();
    let mut glium_display = glium::Display::new(
        glutin::WindowBuilder::new(),
        glutin::ContextBuilder::new(),
        &glutin_events_loop,
    ).unwrap();

    let draw_buffer = nk::NkBuffer::new(&mut nk::NkAllocator::new_vec());

    let font = {
        let mut font = nk::NkUserFont::default();

        // how to initialize font here?
        font
    };

    let mut nk_context = nk::NkContext::new(&mut nk::NkAllocator::new_vec(), &font);
    let mut nk_convert_config = nk::NkConvertConfig::default();

    let mut nk_draw = nuklear_backend_glium::Drawer::new(&mut glium_display, 1024, 1024, 1024, draw_buffer);

    let mut closed = false;
    while !closed {
        let (window_width, window_height) = match glium_display.gl_window().window().get_inner_size() {
            Some(size) => size,
            None => break,
        };

        let mut draw_target = glium_display.draw();

        nk_context.begin(
            "Nuklear Example".into(),
            nk::NkRect {
                x: 0.,
                y: 0.,
                w: 640.,
                h: 480.,
            },
            0,
        );
        nk_context.layout_row(nk::NkLayoutFormat::NK_DYNAMIC, 240.0, &[1.0]);
        nk_context.button_text("hello");

        nk_context.end();

        nk_draw.draw(
            &mut nk_context,
            &mut nk_convert_config,
            &mut draw_target,
            nk::NkVec2 {
                x: window_width as f32,
                y: window_height as f32,
            },
        );

        draw_target.finish().unwrap();

        glutin_events_loop.poll_events(|ev| match ev {
            glutin::Event::WindowEvent { event, .. } => match event {
                glutin::WindowEvent::Closed => closed = true,
                _ => (),
            },
            _ => (),
        });
    }
}
```

However, this errors upon running with:

```
nuklear-c/nuklear/nuklear.h:17269: nk_begin_titled: Assertion `ctx->style.font && ctx->style.font->width && "if this triggers you forgot to add a font"' failed.
```

**Comment by daboross** [comment]
This results in the same error - I don't know the nuklear API though, so I'm probably doing something quite wrong:

```rust
    let mut font_atlas = nk::NkFontAtlas::new(&mut allocator);

    let font = font_atlas
        .add_font_with_bytes(include_bytes!("../OpenSans.ttf"), 10.0)
        .expect("expected add_font_with_bytes to give Some()");

    let mut nk_context = nk::NkContext::new(&mut allocator, font.handle());
```

**Comment by snuk182** [comment]
Because of [this](https://github.com/snuk182/nuklear-test/blob/master/src/main.rs#L332) all the font management is likely to be rewritten. While I filed a [pointer type ticket](https://github.com/snuk182/nuklear-rust/issues/5) for it, I expect deeper changes which affect API, and so the possible documentation. Font management is my 1st prio atm.

**Comment by snuk182** [comment]
As for the direct question of `NkUserFont` management, the answer is: I do not know how to do this directly without [utilizing `NkFontAtlas`/`NkFont`](https://github.com/snuk182/nuklear-test/blob/master/src/main.rs#L134). The original library has `nk_user_font` in its API IMO just because of the drawing API accepting this type of pointers only (and this is done for the font building extensibility purposes). Perhaps if we don't use this feature in Rust, we should not event export this type.

**Comment by daboross** [comment]
Alright, thanks for the info! The nuklear-test repo looks like exactly what I'd be looking for for info on how to use things.

Might I suggest just linking to that repository as an example in this repository's README in lack of any other documentation on things?

**Comment by snuk182** [comment]
Already there, please look at the examples section of the drawing backend descriptions - each backend requires different usage code.

**Comment by daboross** [comment]
Oh! I see it now - thanks! I had missed that.
